<?php
$this->css($this->assetModule('css/front.css'));
$this->jQuery();
// Check class
$class = (isset($class)) ? $class : '';
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta($this->escape($itemSingle['title']), 'og:title', 'property');
$this->headMeta($this->escape($itemSingle['itemUrl']), 'og:url', 'property');
if (isset($description) && !empty($description)) {
    $this->headMeta($this->escape($description), 'og:description', 'property');
}
if (!empty($itemSingle['largeUrl'])) {
    $this->headMeta($this->escape($itemSingle['largeUrl']), 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta($this->escape($itemSingle['title']), 'twitter:title');
if (isset($description) && !empty($description)) {
    $this->headMeta($this->escape($description), 'twitter:description');
}
if (isset($itemSingle['largeUrl']) && !empty($itemSingle['largeUrl'])) {
    $this->headMeta('summary_large_image', 'twitter:card');
    $this->headMeta($this->escape($itemSingle['largeUrl']), 'twitter:image');
}
// Add Geo tags
$this->geoTag($itemSingle['map_latitude'], $itemSingle['map_longitude'], $itemSingle['map_title']);
?>
<div class="clearfix" itemscope itemtype="http://schema.org/LocalBusiness">
    <div class="item-single item-custom">
        <div class="row">
            <div class="col-md-7">

                <div class="clearfix item-head">
                    <div class="itemTitle pull-left">
                        <h1 itemprop="name"><?php echo $this->escape($itemSingle['title']); ?></h1>
                    </div>
                    <?php if ($config['vote_bar'] || $config['vote_bar_review']) { ?>
                        <div class="itemScore pull-right">
                            <?php include $this->template('front/scoremain.phtml'); ?>
                        </div>
                    <?php } ?>
                </div>

                <?php include $this->template('front/gallery'); ?>


                <div class="well clearfix">
                    <ul class="text-muted list-inline text-right pull-right">
                        <li><i class="fa fa-calendar"></i>  <?php echo $this->escape($itemSingle['time_update_view']); ?></li>
                        <li><i class="fa fa-eye"></i> <?php echo _number($this->escape($itemSingle['hits'])); ?></li>
                        <li><?php include $this->template('front/category'); ?></li>
                        <li><i class="fa fa-map-marker"></i> <a title="<?php echo $this->escape($itemSingle['locationInfo']['title']); ?>" href="<?php echo $this->escape($itemSingle['locationInfo']['locationUrl']); ?>"><?php echo $this->escape($itemSingle['locationInfo']['title']); ?></a></li>
                    </ul>
                    <?php if (!empty($itemSingle['city'])) { ?>
                        <ul class="list-inline pull-left">
                            <li><?php echo $this->escape($itemSingle['city']); ?><?php if (!empty($itemSingle['area'])) { ?> | <?php echo $this->escape($itemSingle['area']); ?><?php } ?></li>
                        </ul>
                    <?php } ?>

                    <?php if (!empty($itemSingle['type'])) { ?>
                        <div class="clearfix"><strong><?php _e('Type activity'); ?></strong>
                            : <?php echo $this->escape($itemSingle['type']); ?></div>
                    <?php } ?>
                    <div class="clearfix"><?php include $this->template('front/tag'); ?></div>
                </div>
                <?php include $this->template('front/owner'); ?>

                <div class="clearfix" itemprop="description">
                    <?php echo $itemSingle['text_summary']; ?>
                </div>

                <div class="clearfix" itemprop="description">
                    <?php echo $itemSingle['text_description']; ?>
                </div>


                <div class="clearfix">
                    <?php include $this->template('front/score'); ?>
                </div>

                <?php if ($config['social_sharing']) { ?>
                    <div class="clearfix">
                        <div class="col-md-12 col-sm-12 col-xs-12 socialSharingText">
                            <strong><?php _e('Share if you like'); ?></strong>
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12 socialSharing">
                            <?php echo $this->socialSharing(
                                $config['social_sharing'],
                                $itemSingle['title'],
                                $itemSingle['itemUrl'],
                                $itemSingle['largeUrl']
                            ); ?>
                        </div>
                    </div>
                <?php } ?>



            </div>
            <div class="col-md-5">






                <div class="clearfix item-map" itemscope itemprop="hasMap" itemtype="http://schema.org/Map">
                    <?php if (!empty($itemSingle['map_latitude']) && !empty($itemSingle['map_longitude'])) {
                        $locations = array(
                            'latitude' => $itemSingle['map_latitude'],
                            'longitude' => $itemSingle['map_longitude'],
                            'title' => !empty($itemSingle['map_title']) ? $itemSingle['map_title'] : $itemSingle['title'],
                            'zoom' => !empty($itemSingle['map_zoom']) ? $itemSingle['map_zoom'] : 16,
                        );
                        $option = array(
                            'mapTypeId' => $itemSingle['map_type'],
                        );
                        echo $this->googleMap($locations, $config['map_api_key'], 'point', $option);
                    } ?>
                </div>
                <?php if (!empty($itemSingle['map_latitude']) && !empty($itemSingle['map_longitude'])) { ?>
                    <div class="h-geo hidden" itemprop="geo" itemscope itemtype="http://schema.org/GeoCoordinates">
                        <span class="p-latitude"><?php echo $this->escape($itemSingle['map_latitude']); ?></span>,
                        <span class="p-longitude"><?php echo $this->escape($itemSingle['map_longitude']); ?></span>
                        <meta itemprop="latitude" content="<?php echo $this->escape($itemSingle['map_latitude']); ?>"/>
                        <meta itemprop="longitude" content="<?php echo $this->escape($itemSingle['map_longitude']); ?>"/>
                    </div>
                <?php } ?>



                <div class="well clearfix" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
                    <h2><?php _e('Area informations'); ?></h2>
                    <?php if (!empty($itemSingle['address1'])) { ?>
                        <div class="itemInfoText" itemprop="streetAddress"><strong><?php _e('Address 1'); ?></strong>
                            : <?php echo $this->escape($itemSingle['address1']); ?></div>
                    <?php } ?>
                    <?php if (!empty($itemSingle['address2'])) { ?>
                        <div class="itemInfoText" itemprop="streetAddress"><strong><?php _e('Address 2'); ?></strong>
                            : <?php echo $this->escape($itemSingle['address2']); ?></div>
                    <?php } ?>
                    <?php if (!empty($itemSingle['city'])) { ?>
                        <div class="itemInfoText"><strong><?php _e('City'); ?></strong>
                            : <?php echo $this->escape($itemSingle['city']); ?></div>
                    <?php } ?>
                    <?php if (!empty($itemSingle['zipcode'])) { ?>
                        <div class="itemInfoText"><strong><?php _e('Zip code'); ?></strong>
                            : <?php echo $this->escape($itemSingle['zipcode']); ?></div>
                    <?php } ?>
                    <?php if (!empty($itemSingle['phone1'])) { ?>
                        <div class="itemInfoText" itemprop="telephone"><strong><?php _e('Phone 1'); ?></strong>
                            : <?php echo $this->escape($itemSingle['phone1']); ?></div>
                    <?php } ?>
                </div>
                <?php if (!empty($itemSingle['website'])) { ?>
                    <div class="well clearfix">
                        <h2><?php _e('Data'); ?></h2>
                        <ul class="list-unstyled">
                            <li><a title="<?php _e('Website'); ?>"
                                   href="<?php echo $this->escape($itemSingle['website']); ?>"><i
                                            class="fa fa-external-link"></i> <?php _e('Website'); ?></a></li>
                        </ul>
                    </div>
                <?php } ?>






                <?php include $this->template('front/activity'); ?>
                <?php include $this->template('front/attribute'); ?>
                <?php include $this->template('front/service'); ?>
                <?php include $this->template('front/calendar'); ?>
                <?php include $this->template('front/take-control'); ?>


            </div>
            <div class="col-md-12">

                <div class="clearfix">
                    <?php $eventText = __('There are no event for this item'); ?>
                    <?php include $this->template('front/event'); ?>
                </div>


                <?php include $this->template('front/attach_audio'); ?>
                <?php include $this->template('front/attribute_audio'); ?>
                <?php include $this->template('front/attach_video'); ?>
                <?php include $this->template('front/attribute_video'); ?>
                <?php include $this->template('front/attach'); ?>
                <?php include $this->template('front/review'); ?>
                <?php include $this->template('front/related_free'); ?>
                <?php include $this->template('front/item-list-location'); ?>


            </div>




        </div>
    </div>
</div>
<?php /*





        <div class="clearfix itemUnderHead small">

        </div>
        <?php if (isset($itemSingle['status_type_view']) && $itemSingle['status_type'] > 1) { ?>
            <div class="clearfix">
                <div class="alert alert-danger" role="alert">
                    <i class="fa fa-exclamation-triangle"></i>
                    <?php echo $this->escape($itemSingle['status_type_view']); ?>
                </div>
            </div>
        <?php } ?>
        <div class="clearfix">
            <div class="row" id="stickyContainer">
                <div class="col-md-8">





                </div>
                <div class="col-md-4">
                    <div id="rightSidebar">
                        <?php include $this->template('front/partial/sticky'); ?>



                    </div>
                </div>
            </div>
        </div>


*/ ?>